# Esercizio 1

Definire i  numpy array a=[1.2, 5.4, 6, 1.59] e b=[5.2, 1.2, 1.5, 2] ed eseguire le seguenti operazioni:
  - calcolare la radice quadrata degli elementi di a;
   - calcolare 𝑒xp(𝑎/2) ;
   - calcolare il vettore somma tra a e b ;
   - moltiplicare ogni elemento di a per il corrispondente elemento di b;
   - creare un vettore di valori uniformemente equispaziati tra 0 e 30 con passo  0.5;
   - creare un vettore di 100 valori uniformemente equispaziati tra 1 e 2.
   - usare linspace() per creare un numpy array 2x6 con prima riga di 6 valori uniformi compresi tra 10 e 20 e seconda riga 6 valori     
      uniformi compresi tra  20 e 10;
   - calcolare il prodotto scalare tra a e b;
   - creare la matrice A che ha come righe i vettori a e b ;
   - calcolare il prodotto scalare tra i due vettori a e b;
   - eseguire il prodotto della matrice A per il vettore b e assegnarlo ad y;
   - costruire una matrice diagonale D a partire dal vettore a;

In [ ]:
# per farti uscire le funzioni che puoi usare
# scrivi Oggetto. e schiaccia Tab

import numpy as np
import platform

a=[1.2, 5.4, 6, 1.59] 
b=[5.2, 1.2, 1.5, 2]

print("Valori della matrice a = ", a)
print("Radice quadrata dei elementi di a = ", np.sqrt(a))
print("Esponenziale dei elementi di a/2 = ", np.exp([x/2 for x in a]))
print("Vettore somma :", [ a[x]+b[x] for x in range(len(a))] )

#c = []
#for x in range(len(a)):
#    c.append(a[x] + b[x])

#print(c)

print("Prodotto tra elementi:", [ a[x]*b[x] for x in range(len(a))] )
#print("Vettore che va da 0 a 30", np.arange(0, 30, 0.5))
#print("Vettore con 100 elementi", np.linspace(1,2,100))

#c = np.ones((2, 6))
c = np.array([np.linspace(10,20,6), np.linspace(20,10,6)])
print("Matrice 2x6: ", c)

arr = [ a[x]*b[x] for x in range(len(a))]
s = 0
for x in arr:
    s += x
    
print("Prodotto scalare tra a e b:", s)
print("Altro modo per farlo:", np.sum(arr))

A = np.array([a,b])
print("A = ",A)

y = np.dot(A, b)
print("y = ", y)

print("Diagonale principale: \n", np.diag(a))



# Esercizio 2

Costruire  i seguenti Numpy array 2d utilizzando il minor numero di istruzioni possibili

<img src="ese2.png" width="500">

In [43]:
A = np.concatenate((np.full((3,3),2), np.full((3,1),3)), axis=1)
print(A)

B = np.diag([2 for x in range(3)])
for x in range(11):
    if (x > 0):
        # axis = 1 colonne
        # axis = 0 righe
        B = np.concatenate((B, np.full((3,1),x)), axis=1)       
print(B)

C = np.diag([2 for x in range(5)], k=0) + np.diag([-1 for x in range(4)], k=1) + np.diag([-1 for x in range(4)], k=-1)
print(C)

D = np.concatenate(( (np.full((2,2),2)),(np.full((2,2),3)) ),axis=1) 
D = np.concatenate(( D, np.zeros((2,4)) ),axis=0)
zero_five = np.concatenate(( (np.zeros((2,2))),(np.diag([5 for x in range(2)])) ),axis=1)
D = np.concatenate(( D, zero_five ),axis=0)
print(D)


[[2 2 2 3]
 [2 2 2 3]
 [2 2 2 3]]
[[ 2  0  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  2  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  0  2  1  2  3  4  5  6  7  8  9 10]]
[[ 2 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  2]]
[[2. 2. 3. 3.]
 [2. 2. 3. 3.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


# Esercizio 3

Calcolare la somma dei primi n numeri naturali dispari sia utilizzando un ciclo for che servendosi dell'istruzione sum di numpy.

In [64]:
def sum_natural(n):
    
    s = 0
    arr = [(x*2)+1 for x in range(n)]
    print(arr)
    s = np.sum(arr)
    
    #metodo con for
    #for x in range(n):
        #s += (x*2)+1
    return s

print(sum_natural(5))

[1, 3, 5, 7, 9]
25


# Esercizio 4

Scrivere una function Python per generare l'n-esimo termine (n > 2) della successione
di Fibonacci. Scrivere poi una function ricorsiva che risolva lo stesso problema
e confrontare i tempi di calcolo delle due functions per n = 24.

Ricordiamo la formula per generare i i numeri di Fibonacci:

$$F_0=1$$
$$F_1=1$$
$$F_n = F_{n-1} + F_{n-2}, \quad n=2,...$$

In [8]:
import time

F0 = 1
F1 = 1

def fibonacci(n):
    F_N = 0
    if (n == 0 or n == 1):
        return 1
    else:
        F_N = fibonacci(n-1) + fibonacci(n-2)
        return F_N
        
def norec_fibonacci(n):
    arr = [1, 1]
    x = 0
    y = 1
    if (n == 0 or n == 1):
        return 1
    else:
        while(len(arr) <= n):
            arr.append( arr[x] + arr[y] )
            x+=1
            y+=1
        
        #print(arr)
        return arr[len(arr)-1]

#norec_fibonacci(1)

start_time = time.time()
ris = fibonacci(30)
print("Fatto con la funzione ricorsiva", ris)
end_time = time.time()

print("Tempo che ci ha impegato con la ricorsione: ", (end_time - start_time))

start_time = time.time()
ris = norec_fibonacci(20576)
print("Fatto con la funzione senza ricorsione", ris)
end_time = time.time()

print("Tempo che ci ha impegato senza la ricorsione: ", (end_time - start_time))



Fatto con la funzione ricorsiva 1346269
Tempo che ci ha impegato con la ricorsione:  0.31167101860046387
Fatto con la funzione senza ricorsione 9754127354447731664413464877733194642324162792154990277417906043260981700928350843612737359888951573660962713912365529681569456686655351237894935384042220801220882049324010924553031788263232667669395835460595613868586607590722580174611190230505848926683274986885438381310759325261767284171806619155670742105041612838874997686605998240595985226676071288207099679889619094124815694288115706853096471583308341099304022789310697352409404663792413151019974961646662692476926455507726209503091764128212251301110233774919326592483263183948463380192520278297720868314170290776202527389709110685428211398871370690408919668164274590324631884987684062274915038709235319401019210061505607061585118713722174462056727129101719729228404880964198060054070160193010624331361954960794239717314766327842194808733539019997881113013318654612942104879499538928316485300243367340