## Esercizi sui Numpy array  5 Marzo 2024


**Esercizio 1**

Confrontare il tempo di esecuzione dei due metodi per la creazione di un numpy array di 2000000 di elementi equidistanti nell'intervallo [-4,4]:

    1) costruzione con utilizzo di np.linspace
    
    2) Assegnazione manuale dei valori nel ciclo.
    

In [3]:
import numpy as np
import platform
import time

start_time = time.time()
arr = np.linspace(-4, 4, 2000000)
end_time = time.time()
print("Tempo che ci ha impegato il .linespace", end_time - start_time)

start_time = time.time()
arr = [a for a in range(-4,4)]
single_step = len(arr) / 2000000
arr2 = []
i = -4
while (len(arr2)) < 2000000:
    arr2.append(i)
    i += single_step
end_time = time.time()
print("Tempo che ci ha impegato il while", end_time - start_time)

Tempo che ci ha impegato il .linespace 0.007279157638549805
Tempo che ci ha impegato il while 0.686786413192749


**Esercizio 2**

-     Creare un numpy array 1D (chiamato c) di valori equidistanti tra 7 e 41 con step 2.

-      Trasformare l'array c in un numpy array 2d (chiamato c1) con shape (2,9) usando il metodo .reshape((m,n))

-       Determinare se c1 e' una copia o una vista dell'originale.

In [32]:
#c = np.linspace(7, 41, 17, dtype=int,endpoint=False)
c = np.arange(7, 41+2, 2)
# il +2 serve per far stampare anche il 41

c1 = c.reshape(2, 9).copy()
# array.ndmi per capire la dimensione dell'array
print(c)
print(c1.base)
# se ritorna None è una copia
# se ritorna l'array è un riferimento alla memoria


[ 7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41]
None


**Esercizio 3**

-     Costruire un numpy array 1d, denominato C di valori che variano tra 15 e 41 con step 2

-     Trasformarlo in un numpy array 2d con shape(7,2) usando il metodo . resize(7,2)  che lavora in-place,  (cioè  modifica l'array esistente, non è necessario creare una copia). Verificare la shape di C e dire se C è copia o vista?

In [37]:
C = np.arange(15, 41+2, 2)
print(C)
C.resize(7,2)
print(C)
print(C.base)
# C è una copia

[15 17 19 21 23 25 27 29 31 33 35 37 39 41]
[[15 17]
 [19 21]
 [23 25]
 [27 29]
 [31 33]
 [35 37]
 [39 41]]
None


**Esercizio 4**

-      Costruire il numpy array  s  formato da 100 valori equidistanti in  [0,4],

-      considerarne il reshape in un array 2d che ha 4 righe con un numero opportuno di colonne

In [44]:
s = np.linspace(0,4,100)
print(len(s))
# per ottenere il numero di colonne 100/4 = 25
s.reshape(4, -1)
# il -1 serve per andare a calcolare automaticamente le colonne
# in base a num di di righe e elemnti totali

# .resize modifica la forma e lo fa sul riferimento dell'array

100


array([[0.        , 0.04040404, 0.08080808, 0.12121212, 0.16161616,
        0.2020202 , 0.24242424, 0.28282828, 0.32323232, 0.36363636,
        0.4040404 , 0.44444444, 0.48484848, 0.52525253, 0.56565657,
        0.60606061, 0.64646465, 0.68686869, 0.72727273, 0.76767677,
        0.80808081, 0.84848485, 0.88888889, 0.92929293, 0.96969697],
       [1.01010101, 1.05050505, 1.09090909, 1.13131313, 1.17171717,
        1.21212121, 1.25252525, 1.29292929, 1.33333333, 1.37373737,
        1.41414141, 1.45454545, 1.49494949, 1.53535354, 1.57575758,
        1.61616162, 1.65656566, 1.6969697 , 1.73737374, 1.77777778,
        1.81818182, 1.85858586, 1.8989899 , 1.93939394, 1.97979798],
       [2.02020202, 2.06060606, 2.1010101 , 2.14141414, 2.18181818,
        2.22222222, 2.26262626, 2.3030303 , 2.34343434, 2.38383838,
        2.42424242, 2.46464646, 2.50505051, 2.54545455, 2.58585859,
        2.62626263, 2.66666667, 2.70707071, 2.74747475, 2.78787879,
        2.82828283, 2.86868687, 2.90909091, 2.

**Esercizio 5**

-     Costruire il numpy array s formato da 100 valori equidistanti in  [0,4]
-     considerarne il reshape in un array 2d che ha 4 colonne con un numero opportuno di righe

In [50]:
s = np.linspace(0, 4, 100)
print(len(s))
s1 = s.reshape(-1,4)
print(s1)

100
[[0.         0.04040404 0.08080808 0.12121212]
 [0.16161616 0.2020202  0.24242424 0.28282828]
 [0.32323232 0.36363636 0.4040404  0.44444444]
 [0.48484848 0.52525253 0.56565657 0.60606061]
 [0.64646465 0.68686869 0.72727273 0.76767677]
 [0.80808081 0.84848485 0.88888889 0.92929293]
 [0.96969697 1.01010101 1.05050505 1.09090909]
 [1.13131313 1.17171717 1.21212121 1.25252525]
 [1.29292929 1.33333333 1.37373737 1.41414141]
 [1.45454545 1.49494949 1.53535354 1.57575758]
 [1.61616162 1.65656566 1.6969697  1.73737374]
 [1.77777778 1.81818182 1.85858586 1.8989899 ]
 [1.93939394 1.97979798 2.02020202 2.06060606]
 [2.1010101  2.14141414 2.18181818 2.22222222]
 [2.26262626 2.3030303  2.34343434 2.38383838]
 [2.42424242 2.46464646 2.50505051 2.54545455]
 [2.58585859 2.62626263 2.66666667 2.70707071]
 [2.74747475 2.78787879 2.82828283 2.86868687]
 [2.90909091 2.94949495 2.98989899 3.03030303]
 [3.07070707 3.11111111 3.15151515 3.19191919]
 [3.23232323 3.27272727 3.31313131 3.35353535]
 [3.39393

**Esercizio 6**  

-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo .ravel()  
-     Si tratta di una copia o di una vista?

In [56]:
# 2d matrice nxn
A = np.array([[10,11,12],[13,14,15],[16,17,18]])
A1 = A.ravel()
print(A1)
print(A1.base)

[10 11 12 13 14 15 16 17 18]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


**Esercizio 7**  

-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo  .flatten().
-     Si tratta di una copia o di una vista?

In [57]:
A = np.array([[10,11,12],[13,14,15],[16,17,18]])
A1 = A.flatten()
print(A1)
print(A1.base)

[10 11 12 13 14 15 16 17 18]
None


**Esercizio 8** 

-     creare i due  numpy array 1d
        f1= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]  
        f2= [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
-     "vederli" come matrici  4x4 ed effettuarne il prodotto scalare, memorizzando in f3 la matrice che nasce dal loro prodotto.

In [9]:
f1 = np.array([x for x in range(16)])
f2 = np.array([x for x in range(16,31)])
f1.resize((4,4))
f2.resize((4,4))
f3 = f1 @ f2
print(f3)
#print(f2)

[[ 152  158  164   77]
 [ 504  526  548  353]
 [ 856  894  932  629]
 [1208 1262 1316  905]]


**Esercizio 9**    

 Costruire:
-      Numpy Array A di shape (2,10) : array di valori random campionati da una distribuzione gaussiana con media 0 e varianza 1.
 -     Numpy array 1D B di shape (20,) formato dagli interi da 0 a 19.
 
 "Vedere" A come un array 1D di 20 elementi ed effettuare la somma di A+B



In [20]:
A = np.random.randn(2,10)
print(A)
B = np.array([x for x in range(20)])
print(B)

C = A.flatten() + B
print(C)

[[-0.10609475  0.19897972 -0.72663136 -1.56002299  0.63978905 -0.32695891
  -0.89117791 -0.43437422 -0.31987713 -0.49935112]
 [-0.42746222 -1.66797407  0.3623082  -0.490401    1.47913757  1.137892
  -0.10776053 -1.14703951  0.50332538  0.98667911]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-0.10609475  1.19897972  1.27336864  1.43997701  4.63978905  4.67304109
  5.10882209  6.56562578  7.68012287  8.50064888  9.57253778  9.33202593
 12.3623082  12.509599   15.47913757 16.137892   15.89223947 15.85296049
 18.50332538 19.98667911]


**Esercizio 10** 
-     Creare un array 2D di shape (5,5), denominato B2, con valori tutti uguali a 15.
-     Creare una copia B3 di B2. Modificare l'elemento B3[0,0] assegnandogli il valore 150. 
-     Stampare il numpy array B2 ed il numpy array B3 e verificare che B2, dopo la modifica di B3, è rimasto inalterato

In [19]:
B2 = np.ones((5,5), dtype=int)*15
#print(B2)
B3 = B2.copy()
B3[0][0] = 150
print("Matrice B2: \n", B2)
print("Matrice B3: \n", B3)

Matrice B2: 
 [[15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]]
Matrice B3: 
 [[150  15  15  15  15]
 [ 15  15  15  15  15]
 [ 15  15  15  15  15]
 [ 15  15  15  15  15]
 [ 15  15  15  15  15]]


**Esercizio 11**   

-     Costruire  un numpy array 1D, di shape (10,) denominato  f , costituito da 10 valori equidistanti nell'intervallo [0,1]
-     aumentarne la dimensionalità, in maniera tale che abbia shape (10,1)

In [26]:
f = np.linspace(0,1, 10)
print(f)
f.resize((10,1))
print(f)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[0.        ]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [0.44444444]
 [0.55555556]
 [0.66666667]
 [0.77777778]
 [0.88888889]
 [1.        ]]


- **Esercizio 12**
-     Costruire i seguenti numpy array
      a = np.array([14,13,12,11])
      b = np.array([[4,3,2,1],[9,10,11,12]])

  Costruire il numpy array che si ottiene concatenando a e b per righe


In [28]:
a = np.array([14,13,12,11])
b = np.array([[4,3,2,1],[9,10,11,12]])
c = np.vstack((a,b))
print(c)

[[14 13 12 11]
 [ 4  3  2  1]
 [ 9 10 11 12]]


- **Esercizio 13**
-     Costruire i seguenti numpy array
      a = np.array([14,13,12,11])
      b = np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])

-
- Costruire il numpy array che si ottiene concatenando a e b per colonne

In [39]:
a = np.array([14,13,12,11])
b = np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])
#print(a)
#print(b)
a.resize(4,1)
print(a)
c = np.hstack((b,a))
print(c)

[[14]
 [13]
 [12]
 [11]]
[[ 4  3  2  1 14]
 [ 9 10 11 12 13]
 [ 4  3  2  1 12]
 [ 9 10 11 12 11]]


**Esercizio 14**

Costruire, facendo uso di una sola riga di codice, la matrice A di ordine 10, che ha gli unici elementi diversi da zero, sulla diagonale principale, sulla codiagonale inferiore e sulla codiagonale superiore:

elementi diagonali $A_{i,i}=10 \quad$, i=1,20

elementi nella codiagonale inferiore $A_{i-1,i}=-12, \quad$ i=2,..,20, 

elementi nella codiagonale superiore $A_{i,i+1}=-2 \quad$ i=1,..,19

In [44]:
A = np.diag([10 for x in range(20)], k=0) + np.diag([-2 for x in range(19)], k=1) + np.diag([-12 for x in range(19)], k=-1)
print(A)

[[ 10  -2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [-12  10  -2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0 -12  10  -2   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0 -12  10  -2   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0 -12  10  -2   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0 -12  10  -2   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0 -12  10  -2   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0 -12  10  -2   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0 -12  10  -2   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0   0 -12  10  -2   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0   0   0 -12  10  -2   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0   0   0   0 -12  10  -2   0   0   0

**Esercizio 15**

Costruire la matrice identità, denominata *I*,  della stessa dimensione di *A*

In [50]:
C = np.identity(A.size)
print(C)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


**Esercizio 16**

Facendo uso dell'operatore slicing *:* ,costruire la matrice AA selezionando dalla matrice A le righe che vanno dalla 2 alla 9 con step 2 e le colonne che vanno dalla 3 alla 6 con step 2.
La matrice AA è una vista o una copia?


In [55]:
AA = A[2:9:2,3:6:2]

print(AA)
print("Vista(riferimento) o copia? ", AA.base)

[[ -2   0]
 [-12  -2]
 [  0 -12]
 [  0   0]]
Vista(riferimento) o copia?  [[ 10  -2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [-12  10  -2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0 -12  10  -2   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0 -12  10  -2   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0 -12  10  -2   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0 -12  10  -2   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0 -12  10  -2   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0 -12  10  -2   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0 -12  10  -2   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0   0 -12  10  -2   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0   0   0 -12  10  -2   0   0   0   0   0   0
  

**Esercizio 17**

Facendo uso dell'operatore slicing *:*, costruire la matrice A1 selezionando dalla matrice A le colonne che vanno dalla 1 alla 5 con step 2.  Trasforma la matrice A1 in una copia.

In [57]:
A1 = np.array(A[:,1:5:2])

print(A1)
print("Vista(riferimento) o copia? ", A1.base)

[[ -2   0]
 [ 10   0]
 [-12  -2]
 [  0  10]
 [  0 -12]
 [  0   0]
 [  0   0]
 [  0   0]
 [  0   0]
 [  0   0]
 [  0   0]
 [  0   0]
 [  0   0]
 [  0   0]
 [  0   0]
 [  0   0]
 [  0   0]
 [  0   0]
 [  0   0]
 [  0   0]]
Vista(riferimento) o copia?  None


**Esercizio 18**

Costruisci due numpy array A e B di shape (5,5) 
   - A formata da numeri interi casuali  nell'intervallo [1,20]
   - B formata da numeri interi casuali  nell'intervallo [1,6]
 
  Costruisci con una sola riga di codice le seguenti matrici
  
  C=A+B   dove  $\quad c_{ij}=a_{ij}+b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  D=A-B   dove  $\quad d_{ij}=a_{ij}-b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  E=A*B   dove  $\quad e_{ij}=a_{ij}*b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  F=A\B   dove  $\quad f_{ij}=a_{ij}\b_{ij} \quad i=0,..,n, \quad j=0,...,n$

In [39]:
A = np.random.randint(1, 21, (5,5))
print("Matrice A:\n",A)
B = np.random.randint(1, 7, (5,5))
print("Matrice B:\n",B)

C , D , E , F = A + B , A - B , A * B , A / B
print("Somma tra A e B:\n", C)
print("Sottrazione tra A e B:\n", D)
print("Moltiplicazione tra A e B:\n", E)
print("Divisione tra A e B:\n", F)


Matrice A:
 [[16 13 20 13 14]
 [13 20 18  7  5]
 [20  9 11 15 19]
 [ 1  3  1  3 14]
 [18  2 11  5  5]]
Matrice B:
 [[4 3 2 6 3]
 [1 1 4 1 3]
 [4 3 4 2 5]
 [4 1 3 1 1]
 [6 2 3 2 1]]
Somma tra A e B:
 [[20 16 22 19 17]
 [14 21 22  8  8]
 [24 12 15 17 24]
 [ 5  4  4  4 15]
 [24  4 14  7  6]]
Sottrazione tra A e B:
 [[12 10 18  7 11]
 [12 19 14  6  2]
 [16  6  7 13 14]
 [-3  2 -2  2 13]
 [12  0  8  3  4]]
Moltiplicazione tra A e B:
 [[ 64  39  40  78  42]
 [ 13  20  72   7  15]
 [ 80  27  44  30  95]
 [  4   3   3   3  14]
 [108   4  33  10   5]]
Divisione tra A e B:
 [[ 4.          4.33333333 10.          2.16666667  4.66666667]
 [13.         20.          4.5         7.          1.66666667]
 [ 5.          3.          2.75        7.5         3.8       ]
 [ 0.25        3.          0.33333333  3.         14.        ]
 [ 3.          1.          3.66666667  2.5         5.        ]]


**Esercizio 19**

Costruisci la matrice ottenuta facendo il prodotto scalare tra le  matrici A e B (righe per colonne)

In [14]:
C = A @ B
print(C)


[[219 220 250 189 195]
 [272 240 294 243 206]
 [172 209 207 136 195]
 [145 171 138 107 134]
 [283 225 314 259 251]]


**Esercizio 20**

Costruisci l'array ottenuto sommando gli elementi delle righe della matrice B usando l'appropriata funzione di Numpy.

In [17]:
# axis = 1 per sommare le righe
# //   = 0 per sommare le colonne
s1 = np.sum(B, axis=1)
# ottieni un'array con la somma delle righe
# singolarmente
print(s1)

[19 26 18 22 23]


**Esercizio 21** 

Costruisci l'array ottenuto sommando gli elementi delle colonne della matrice B usando l'appropriata funzione di Numpy.

In [18]:
s0 = np.sum(B , axis=0)
print(s0)

[23 20 24 20 21]


**Esercizio 22** 

Somma tutti gli elementi di B usando l'appropriata funzione di Numpy.

In [27]:
s3 = np.sum(B)
print(s3)

85


**Esercizio 23**

Calcolare il minimo degli elementi di B, tra le righe, tra le colonne, il minimo di tutta la matrice B

In [29]:
min0 = np.min(B, axis=0)
min1 = np.min(B, axis=1)
min3 = np.min(B)
print("Minimo rispetto righe: ", min0)
print("Minimo rispetto colonne: ", min1)
print("Minimo rispetto a tutto B: ", min3)

Minimo rispetto righe:  [2 2 1 1 2]
Minimo rispetto colonne:  [1 1 1 3 2]
Minimo rispetto a tutto B:  1


**Esercizio 24**

Calcola e memorizza in un vettore la somma degli elementi di ogni colonna di $ |B |$. Calcola successivamente il massimo di questo vettore.
$maxsc= \max_{j=1,n} \sum_{i} |b_{ij}|$

In [30]:
ris = np.max(np.sum(B, axis=1))
print(ris)

20


**Esercizio 25**
Calcola, memorizzando in un vettore, la somma degli elementi di ogni riga  di $ |B |$. Calcola successivamente il massimo di questo vettore.
$maxsr= \max_{i=1,n} \sum_{j} |b_{ij}|$

In [31]:
ris2 = np.max(np.sum(B, axis=0))
print(ris2)

24


**Esercizio 26**

Effettua nella matrice B lo scambio tra la  riga 2 e  la riga 3

In [42]:
print(B)
tmp = np.array(B[1,:])
print("\n")
B[1,:] = np.array(B[2,:])
B[2,:] = tmp
print(B)

[[4 3 2 6 3]
 [1 1 4 1 3]
 [4 3 4 2 5]
 [4 1 3 1 1]
 [6 2 3 2 1]]


[[4 3 2 6 3]
 [4 3 4 2 5]
 [1 1 4 1 3]
 [4 1 3 1 1]
 [6 2 3 2 1]]


**Esercizio 27**

Calcola il valore massimo della colonna 0-esima della matrice B e l'indice di riga a cui appartiene

In [49]:
m = np.max(B[:,0])
print(m)
print(np.argwhere(B[:,0] == m))

6
[[4]]


**Esercizio 28**   


Scrivi una funzione border(m,n,visualizza=False) che:
-      crea un array 2D di shape(m,n) che abbia tutti valori nulli
-     imposta ad 1  i valori degli elementi sul bordo dell'array (prima ed ultima riga, prima e l'ultima colonna)
-      Preveda un argomento di default che se impostato a True visualizza la matrice

In [87]:
def border(m, n, visualiza=False):
    arr = np.zeros((m,n), dtype=int)
    row_one = np.ones((1,n), dtype=int)
    col_one = np.ones((1,m), dtype=int)
    # primo modo
    arr[0,:] = row_one
    arr[m-1,:] = row_one
    #print(arr)
    arr[:,n-1] = col_one
    arr[:,0] = col_one
    
    # secondo modo
    #for i in range(n):
        #arr[i,0] = 1
        #arr[i,n-1] = 1
    #arr[:,n-1] = col_one
    #print(np.ones((1,m), dtype=int))
    print(arr)

border(3,10)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


**Esercizio 29**

Scrivi una funzione `visualizza(f,a,b)`che prende in input una lambda function f, gli estremi dell'intervallo [a,b] su cui è definita e la visualizzi in una finestra grafica

Chaima la funzione passandogli la funzione f(x)=sin(2*$\pi$*x), [a,b]=[0,2*$\pi$]

**Esercizio 30**

Scrivi una funzione `visualizza2(f,a,b,f2,a2,b2)`che prende in input una lambda function f e gli estremi dell'intervallo [a,b]  su cui è definita, una lambda function f2 e gli estremi dell'intervallo su cui è definita [a2,b2] e le visualizzi sulla stessa finestra grafica.

Chaima la funzione passandogli  una funzione f(x) quadratica ed una funzione f2(x) exponenziale ed [a,b]=[0,2]