## Esercizi sui Numpy array  5 Marzo 2024


**Esercizio 1**

Confrontare il tempo di esecuzione dei due metodi per la creazione di un numpy array di 2000000 di elementi equidistanti nell'intervallo [-4,4]:

    1) costruzione con utilizzo di np.linspace
    
    2) Assegnazione manuale dei valori nel ciclo.
    

In [42]:
import numpy as np
import time

a = -4
b = 4
num_elem = 2000000

start_time = time.time()
arr1 = np.linspace(a, b, num_elem)
end_time = time.time()

print("Tempo impiegato dalla funzione = ", end_time - start_time)

arr2 = []
inc_elem = (np.abs(a)+b)/num_elem
tmp = a

start_time = time.time()
for x in range(num_elem):
    arr2.append(tmp)
    tmp =+ inc_elem
    
end_time = time.time()

#print(len(arr2))

print("Tempo impiegato dal ciclo = ", end_time - start_time)


Tempo impiegato dalla funzione =  0.007013559341430664
Tempo impiegato dal ciclo =  0.33724164962768555


**Esercizio 2**

-     Creare un numpy array 1D (chiamato c) di valori equidistanti tra 7 e 41 con step 2.

-      Trasformare l'array c in un numpy array 2d (chiamato c1) con shape (2,9) usando il metodo .reshape((m,n))

-       Determinare se c1 e' una copia o una vista dell'originale.

In [20]:
c = np.arange(7, 42, 2)
print(c)

c1 = c.reshape((2,9))
print(c1)

print(c1.base) # è una vista, se restituiva None era una copia

[ 7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41]
[[ 7  9 11 13 15 17 19 21 23]
 [25 27 29 31 33 35 37 39 41]]
[ 7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41]


**Esercizio 3**

-     Costruire un numpy array 1d, denominato $C$ di valori che variano tra 15 e 41 con step 2

-     Trasformarlo in un numpy array 2d con shape(7,2) usando il metodo . resize(7,2)  che lavora in-place,  (cioè  modifica l'array esistente, non è necessario creare una copia). Verificare la shape di C e dire se C è copia o vista?

In [27]:
C = np.arange(15, 42, 2)
C.resize(7,2)
print("shape C", C.shape)
print(C.base) # è una Copia

shape C (7, 2)
None


**Esercizio 4**

-      Costruire il numpy array  s  formato da 100 valori equidistanti in  [0,4],

-      considerarne il reshape in un array 2d che ha 4 righe con un numero opportuno di colonne

In [39]:
s = np.linspace(0, 4, 100)

s.reshape(4, -1)


array([[0.        , 0.04040404, 0.08080808, 0.12121212, 0.16161616,
        0.2020202 , 0.24242424, 0.28282828, 0.32323232, 0.36363636,
        0.4040404 , 0.44444444, 0.48484848, 0.52525253, 0.56565657,
        0.60606061, 0.64646465, 0.68686869, 0.72727273, 0.76767677,
        0.80808081, 0.84848485, 0.88888889, 0.92929293, 0.96969697],
       [1.01010101, 1.05050505, 1.09090909, 1.13131313, 1.17171717,
        1.21212121, 1.25252525, 1.29292929, 1.33333333, 1.37373737,
        1.41414141, 1.45454545, 1.49494949, 1.53535354, 1.57575758,
        1.61616162, 1.65656566, 1.6969697 , 1.73737374, 1.77777778,
        1.81818182, 1.85858586, 1.8989899 , 1.93939394, 1.97979798],
       [2.02020202, 2.06060606, 2.1010101 , 2.14141414, 2.18181818,
        2.22222222, 2.26262626, 2.3030303 , 2.34343434, 2.38383838,
        2.42424242, 2.46464646, 2.50505051, 2.54545455, 2.58585859,
        2.62626263, 2.66666667, 2.70707071, 2.74747475, 2.78787879,
        2.82828283, 2.86868687, 2.90909091, 2.

**Esercizio 5**

-     Costruire il numpy array s formato da 100 valori equidistanti in  [0,4]
-     considerarne il reshape in un array 2d che ha 4 colonne con un numero opportuno di righe

In [40]:
s = np.linspace(0, 4, 100)

s.reshape(-1, 4)

array([[0.        , 0.04040404, 0.08080808, 0.12121212],
       [0.16161616, 0.2020202 , 0.24242424, 0.28282828],
       [0.32323232, 0.36363636, 0.4040404 , 0.44444444],
       [0.48484848, 0.52525253, 0.56565657, 0.60606061],
       [0.64646465, 0.68686869, 0.72727273, 0.76767677],
       [0.80808081, 0.84848485, 0.88888889, 0.92929293],
       [0.96969697, 1.01010101, 1.05050505, 1.09090909],
       [1.13131313, 1.17171717, 1.21212121, 1.25252525],
       [1.29292929, 1.33333333, 1.37373737, 1.41414141],
       [1.45454545, 1.49494949, 1.53535354, 1.57575758],
       [1.61616162, 1.65656566, 1.6969697 , 1.73737374],
       [1.77777778, 1.81818182, 1.85858586, 1.8989899 ],
       [1.93939394, 1.97979798, 2.02020202, 2.06060606],
       [2.1010101 , 2.14141414, 2.18181818, 2.22222222],
       [2.26262626, 2.3030303 , 2.34343434, 2.38383838],
       [2.42424242, 2.46464646, 2.50505051, 2.54545455],
       [2.58585859, 2.62626263, 2.66666667, 2.70707071],
       [2.74747475, 2.78787879,

**Esercizio 6**  

-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo .ravel()  
-     Si tratta di una copia o di una vista?

In [51]:
A = np.array([[10,11,12],[13,14,15],[16,17,18]])
print(A)
A1 = A.ravel()
#print(A1)
print(A1.base) # con ravel è una vista

[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


**Esercizio 7**  

-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo  .flatten().
-     Si tratta di una copia o di una vista?

In [52]:
A = np.array([[10,11,12],[13,14,15],[16,17,18]])
A1 = A.flatten()
print(A1.base) # con flatten è una copia

None


**Esercizio 8** 

-     creare i due  numpy array 1d
        f1= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]  
        f2= [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
-     "vederli" come matrici  4x4 ed effettuarne il prodotto scalare, memorizzando in f3 la matrice che nasce dal loro prodotto.

In [59]:
f1 = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
f2 = np.array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])
f1.resize(4,4)
f2.resize(4,4)

f3 = f1 @ f2
print(f3)

[[ 152  158  164  170]
 [ 504  526  548  570]
 [ 856  894  932  970]
 [1208 1262 1316 1370]]


**Esercizio 9**    

 Costruire:
-      Numpy Array A di shape (2,10) : array di valori random campionati da una distribuzione gaussiana con media 0 e varianza 1.
 -     Numpy array 1D B di shape (20,) formato dagli interi da 0 a 19.
 
 "Vedere" A come un array 1D di 20 elementi ed effettuare la somma di A+B



In [75]:
A = np.random.rand(2, 10)
print(arr)
B = np.array([x for x in range(20)])

# NOTA: (20,) significa 1 riga e 20 colonne
print(arr2.shape)
C = A.flatten() + B
print(C)

[[0.04919266 0.73978469 0.68107377 0.72076157 0.54178709 0.10542441
  0.45761399 0.51051368 0.70296371 0.86698382]
 [0.09083783 0.05192941 0.16759106 0.72021005 0.12770426 0.46836196
  0.76641758 0.36361088 0.52818962 0.19824197]]
(20,)
[ 0.05725917  1.56418136  2.18349303  3.80769614  4.6372896   5.19768316
  6.91313382  7.01545762  8.61373248  9.53207129 10.54205957 11.94063319
 12.88313048 13.45555311 14.68196401 15.08702592 16.64811372 17.64479509
 18.62610134 19.25116483]


**Esercizio 10** 
-     Creare un array 2D di shape (5,5), denominato B2, con valori tutti uguali a 15.
-     Creare una copia B3 di B2. Modificare l'elemento B3[0,0] assegnandogli il valore 150. 
-     Stampare il numpy array B2 ed il numpy array B3 e verificare che B2, dopo la modifica di B3, è rimasto inalterato

In [82]:
B2 = np.full((5,5), 15)
print(B2)
B3 = B2.copy()
#print(B3.base)
B3[0,0] = 150
print(B3)
print(B2)

[[15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]]
[[150  15  15  15  15]
 [ 15  15  15  15  15]
 [ 15  15  15  15  15]
 [ 15  15  15  15  15]
 [ 15  15  15  15  15]]
[[15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]]


**Esercizio 11**   

-     Costruire  un numpy array 1D, di shape (10,) denominato  f , costituito da 10 valori equidistanti nell'intervallo [0,1]
-     aumentarne la dimensionalità, in maniera tale che abbia shape (10,1)

In [94]:
f = np.linspace(0,1,10)
print(len(f))
f.resize(10,1)
print(f)

10
[[0.        ]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [0.44444444]
 [0.55555556]
 [0.66666667]
 [0.77777778]
 [0.88888889]
 [1.        ]]


- **Esercizio 12**
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12]])

  Costruire il numpy array che si ottiene concatenando a e b per righe


In [96]:
a=np.array([[14,13,12,11]])
b=np.array([[4,3,2,1],[9,10,11,12]])

c = np.concatenate((a,b), axis=0)
print(c)

[[14 13 12 11]
 [ 4  3  2  1]
 [ 9 10 11 12]]


- **Esercizio 13**
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])

-
- Costruire il numpy array che si ottiene concatenando a e b per colonne

In [102]:
a=np.array([14,13,12,11])
b=np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])
print(b)
a.resize(4,1)
c = np.hstack((a,b))
print(c)


[[ 4  3  2  1]
 [ 9 10 11 12]
 [ 4  3  2  1]
 [ 9 10 11 12]]
[[14  4  3  2  1]
 [13  9 10 11 12]
 [12  4  3  2  1]
 [11  9 10 11 12]]


**Esercizio 14**

Costruire, facendo uso di una sola riga di codice, la matrice A di ordine 10, che ha gli unici elementi diversi da zero, sulla diagonale princiaple, sulla codiagonale inferiore e sulla codiagonale superiore:

elementi diagonali $A_{i,i}=10 \quad$, i=1,20

elementi nella codiagonale inferiore $A_{i-1,i}=-12, \quad$ i=2,..,20, 

elementi nella codiagonale superiore $A_{i,i+1}=-2 \quad$ i=1,..,19

In [113]:
A = (np.eye(20, k=0) * 10) + (np.eye(20, k=1) * -2) + (np.eye(20, k=-1) * -12)
print(A)


[[ 10.  -2.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [-12.  10.  -2.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0. -12.  10.  -2.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0. -12.  10.  -2.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. -12.  10.  -2.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0. -12.  10.  -2.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. -12.  10.  -2.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0. -12.  10.  -2.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0. -12.  10.  -2.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. -12.  10.  -2

**Esercizio 15**

Costruire la matrice identità, denominata *I*,  della stessa dimensione di *A*

In [123]:
print(len(A)) # ottieni il numero di righe di A
B = np.eye(len(A), k=0)
print(B)
print(B.shape)

20
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.

**Esercizio 16**

Facendo uso dell'operatore slicing *:* ,costruire la matrice AA selezionando dalla matrice A le righe che vanno dalla 2 alla 9 con step 2 e le colonne che vanno dalla 3 alla 6 con step 2.
La matrice AA è una vista o una copia?


In [122]:
AA = A[2:9:2, 3:6:2]
print(AA)
print(AA.base) # è una vista

[[ -2.   0.]
 [-12.  -2.]
 [  0. -12.]
 [  0.   0.]]
[[ 10.  -2.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [-12.  10.  -2.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0. -12.  10.  -2.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0. -12.  10.  -2.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. -12.  10.  -2.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0. -12.  10.  -2.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. -12.  10.  -2.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0. -12.  10.  -2.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0. -12.  10.  -2.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [

**Esercizio 17**

Facendo uso dell'operatore slicing *:*, costruire la matrice A1 selezionando dalla matrice A le colonne che vanno dalla 1 alla 5 con step 2.  Trasforma la matrice A1 in una copia.

In [125]:
A1 = A[:,0:4:2]
print(A1)
A1 = A1.copy()
print(A1.base)

[[ 10.   0.]
 [-12.  -2.]
 [  0.  10.]
 [  0. -12.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]]
None


**Esercizio 18**

Costruisci due numpy array A e B di shape (5,5) 
   - A formata da numeri interi casuali  nell'intervallo [1,20]
   - B formata da numeri interi casuali  nell'intervallo [1,6]
 
  Costruisci con una sola riga di codice le seguenti matrici
  
  C=A+B   dove  $\quad c_{ij}=a_{ij}+b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  D=A-B   dove  $\quad d_{ij}=a_{ij}-b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  E=A*B   dove  $\quad e_{ij}=a_{ij}*b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  F=A\B   dove  $\quad f_{ij}=a_{ij}\b_{ij} \quad i=0,..,n, \quad j=0,...,n$

In [130]:
A = np.random.randint(1,21, (5,5))
B = np.random.randint(1,7, (5,5))
print(A)
print(B)

C = A + B
D = A - B
E = A * B
F = A / B
print("C :\n", C)
print("D :\n", D)
print("E :\n", E)
print("F :\n", F)

[[20  6 13 16 11]
 [ 3 17  9 12 14]
 [18 11  7 14  9]
 [15 11 16 12 10]
 [17 11 17 15  4]]
[[2 5 3 6 6]
 [2 3 1 5 4]
 [4 6 5 6 1]
 [5 4 4 4 3]
 [6 6 6 5 1]]
C :
 [[22 11 16 22 17]
 [ 5 20 10 17 18]
 [22 17 12 20 10]
 [20 15 20 16 13]
 [23 17 23 20  5]]
D :
 [[18  1 10 10  5]
 [ 1 14  8  7 10]
 [14  5  2  8  8]
 [10  7 12  8  7]
 [11  5 11 10  3]]
E :
 [[ 40  30  39  96  66]
 [  6  51   9  60  56]
 [ 72  66  35  84   9]
 [ 75  44  64  48  30]
 [102  66 102  75   4]]
F :
 [[10.          1.2         4.33333333  2.66666667  1.83333333]
 [ 1.5         5.66666667  9.          2.4         3.5       ]
 [ 4.5         1.83333333  1.4         2.33333333  9.        ]
 [ 3.          2.75        4.          3.          3.33333333]
 [ 2.83333333  1.83333333  2.83333333  3.          4.        ]]


**Esercizio 19**

Costruisci la matrice ottenuta facendo il prodotto scalare tra le  matrici A e B (righe per colonne)

In [131]:
F = A @ B
print("F =\n", F)

F =
 [[250 326 261 347 216]
 [220 252 203 275 145]
 [210 275 210 306 210]
 [236 312 244 339 196]
 [223 304 231 339 212]]


**Esercizio 20**

Costruisci l'array ottenuto sommando gli elementi delle righe della matrice B usando l'appropriata funzione di Numpy.

In [132]:
print(np.sum(B, axis=1))

[22 15 22 20 24]


**Esercizio 21** 

Costruisci l'array ottenuto sommando gli elementi delle colonne della matrice B usando l'appropriata funzione di Numpy.

In [133]:
print(np.sum(B, axis=0))

[19 24 19 26 15]


**Esercizio 22** 

Somma tutti gli elementi di B usando l'appropriata funzione di Numpy.

**Esercizio 23**

Calcolare il minimo degli elementi di B, tra le righe, tra le colonne, il minimo di tutta la matrice B

**Esercizio 24**

Calcola e memorizza in un vettore la somma degli elementi di ogni colonna di $ |B |$. Calcola successivamente il massimo di questo vettore.
$maxsc= \max_{j=1,n} \sum_{i} |b_{ij}|$

**Esercizio 25**
Calcola, memorizzando in un vettore, la somma degli elementi di ogni riga  di $ |B |$. Calcola successivamente il massimo di questo vettore.
$maxsr= \max_{i=1,n} \sum_{j} |b_{ij}|$

**Esercizio 26**

Effettua nella matrice B lo scambio tra la  riga 2 e  la riga 3

**Esercizio 27**

Calcola il valore massimo della colonna 0-esima della matrice B e l'indice di riga a cui appartiene

**Esercizio 28**   


Scrivi una funzione border(m,n,visualizza=False) che:
-      crea un array 2D di shape(m,n) che abbia tutti valori nulli
-     imposta ad 1  i valori degli elementi sul bordo dell'array (prima ed ultima riga, prima e l'ultima colonna)
-      Preveda un argomento di default che se impostato a True visualizza la matrice

**Esercizio 29**

Scrivi una funzione `visualizza(f,a,b)`che prende in input una lambda function f, gli estremi dell'intervallo [a,b] su cui è definita e la visualizzi in una finestra grafica

Chaima la funzione passandogli la funzione f(x)=sin(2*$\pi$*x), [a,b]=[0,2*$\pi$]

**Esercizio 30**

Scrivi una funzione `visualizza2(f,a,b,f2,a2,b2)`che prende in input una lambda function f e gli estremi dell'intervallo [a,b]  su cui è definita, una lambda function f2 e gli estremi dell'intervallo su cui è definita [a2,b2] e le visualizzi sulla stessa finestra grafica.

Chaima la funzione passandogli  una funzione f(x) quadratica ed una funzione f2(x) exponenziale ed [a,b]=[0,2]